- .dockerignore
- .gitignore
- docker-compose.yaml
- docs/README-SONAR.md
- pom.xml
Added a Local SonarQube support
> Added a Local SonarQube support 

- src/main/java/com/zufar/onlinestore/cart/CartApi.java
- src/main/java/com/zufar/onlinestore/cart/dto/AddNewItemToShoppingSessionRequest.java
- src/main/java/com/zufar/onlinestore/cart/dto/GetShoppingSessionRequest.java
- src/main/java/com/zufar/onlinestore/cart/dto/RemoveItemFromShoppingSessionRequest.java
- src/main/java/com/zufar/onlinestore/cart/dto/ShoppingSession.java
- src/main/java/com/zufar/onlinestore/cart/dto/UpdateProductAmountInShoppingSessionItemRequest.java
- src/main/java/com/zufar/onlinestore/cart/dto/UpdateProductsQuantityInShoppingSessionItemRequest.java
https://trello.com/c/ARGnvUGg/38-cart-2-create-interface-for-cart-api-24-07-2023
> [cart-2] Cart API was added

- src/main/resources/db/changelog/version-1.0/21.07.2023.part3.insert-shopping-session-data.sql
Changes:
21.07.2023.part3.insert-shopping-session-data.sql was modified: test data of userIds from user_details table were added to shopping_session table 
Conclusion:
Project was built with Apache Maven successfully.
> Cart-9: Fix user_id in sql 

- src/main/java/com/zufar/onlinestore/common/response/ApiResponse.java
1. Task's name:
[common-1] Сreate generic ApiResponse wrapper
2. Developer's full name:
Konstantin Nyamtsu
3. Link to the PR: 
https://github.com/Sunagatov/Online-Store/pull/62
4. Link to Documentation:
https://github.com/Sunagatov/Online-Store/wiki/Api-Specification-for-Payment
5. Changes:
- Added generic ApiResponse wrapper
6. Tests:
The change was tested with using postman in the form of a universal json response from endpoints.
7. Test data:
Use any endpoint in the project and check response body of the endpoint
8. Conclusion:
Project was built with Apache Maven successfully.
Project was tested manually with Postman successfully.
> [common-1]: Create generic ApiResponse wrapper

- .gitignore
- pom.xml
- src/main/java/com/zufar/onlinestore/payment/converter/PaymentConverter.java
- src/main/java/com/zufar/onlinestore/payment/converter/PaymentIntentConverter.java
- src/main/java/com/zufar/onlinestore/payment/converter/PaymentMethodConverter.java
- src/main/java/com/zufar/onlinestore/payment/dto/PaymentDetailsDto.java
- src/main/java/com/zufar/onlinestore/payment/dto/PriceDetailsDto.java
- src/main/java/com/zufar/onlinestore/payment/endpoint/PaymentEndpoint.java
- src/main/java/com/zufar/onlinestore/payment/service/PaymentCreator.java
- src/main/java/com/zufar/onlinestore/payment/service/PaymentRetriever.java
1. Task's name:
[payment-7] Replace converter classes of Payment package with Mapstruct
2. Developer's full name:
Vitalii Bredun
3. Link to the PR: 
https://github.com/Sunagatov/Online-Store/pull/65
4. Link to Documentation:
https://github.com/Sunagatov/Online-Store/wiki/Api-Specification-for-Payment
5. Changes:
- Added the Mapstruct interfaces to the converter package.
- Deleted the custom mapper classes.
6. Tests:
_1. I registered a new user with the JWT registration endpoint using Postman. New JWT token was returned as expected. Then I checked that this user was saved in the database as expected.
_2. I authenticated the existed user using his username and password with the JWT auth endpoint using Postman. New JWT token was returned as expected. 
_3. I sent the payment method request …
> [payment-7]: Replace converter classes of Payment package with Mapstruct

- docker-compose.services.yml
- docker-compose.yml
Add new docker-compose.services.yml
> Restructure Docker flow

- docs/qa/checklists/PAYMENT_BE.md
The checklist is described in this documentation https://github.com/Sunagatov/Online-Store/wiki/Api-Specification-for-Payment
> [QA] Creation checklist for Payment API

- src/main/java/com/zufar/onlinestore/common/exception/handler/GlobalExceptionHandler.java
- src/main/java/com/zufar/onlinestore/common/response/ApiResponse.java
- src/main/java/com/zufar/onlinestore/payment/exception/handler/PaymentExceptionHandler.java
> [issue-2] Fixed response for case when user input invalid authentication data

- pom.xml
- product-openapi.yaml
- src/main/java/com/zufar/onlinestore/product/endpoint/ProductsEndpoint.java
- src/main/resources/product-openapi.yaml
1. Task's name: 
[product-5] add OpenAPI for product package
2. Developer's full name: 
Vitalii Bredun
3. Link to the PR: 
https://github.com/Sunagatov/Online-Store/pull/93
4. Link to Documentation: 
https://github.com/Sunagatov/Online-Store/wiki/API-Specification-for-Product
5. Changes: 
- Added yaml file documentation of product API.
6. Conclusion: 
Project was built with Apache Maven successfully.
> [product-5] add OpenAPI for product package

- pom.xml
- src/main/java/com/zufar/onlinestore/product/endpoint/ProductsEndpoint.java
- src/main/java/com/zufar/onlinestore/security/api/UserAuthenticationService.java
- src/main/java/com/zufar/onlinestore/security/api/UserRegistrationService.java
- src/main/java/com/zufar/onlinestore/security/api/UserSecurityManager.java
- src/main/java/com/zufar/onlinestore/security/converter/RegistrationDtoConverter.java
- src/main/java/com/zufar/onlinestore/security/dto/UserAuthenticationRequest.java
- src/main/java/com/zufar/onlinestore/security/dto/UserAuthenticationResponse.java
- src/main/java/com/zufar/onlinestore/security/dto/UserRegistrationRequest.java
- src/main/java/com/zufar/onlinestore/security/dto/UserRegistrationResponse.java
- src/main/java/com/zufar/onlinestore/security/dto/authentication/UserAuthenticationResponse.java
- src/main/java/com/zufar/onlinestore/security/endpoint/UserSecurityEndpoint.java
- src/main/resources/api-specs/security-openapi.yaml
> IL-68 Add OpenAPI for security package

- src/test/java/com/zufar/onlinestore/exception/handler/JwtTokenExceptionsHandlerTest.java
- src/test/java/com/zufar/onlinestore/security/configuration/SpringSecurityConfigurationTest.java
I need help with testing the security/configuration and security/exception packages
> IL-113: Cover Security  package with unit tests

- src/main/java/com/zufar/icedlatte/favorite/api/AddProductsToFavoriteList.java
- src/main/java/com/zufar/icedlatte/favorite/converter/FavoriteItemDtoConverter.java
- src/main/java/com/zufar/icedlatte/favorite/converter/FavoriteListDtoConverter.java
- src/main/java/com/zufar/icedlatte/favorite/converter/ListOfFavoriteProductsDtoConverter.java
- src/main/java/com/zufar/icedlatte/favorite/dto/FavoriteItemDto.java
- src/main/java/com/zufar/icedlatte/favorite/dto/FavoriteListDto.java
- src/main/java/com/zufar/icedlatte/favorite/endpoint/FavoritesEndpoint.java
- src/main/java/com/zufar/icedlatte/favorite/entity/FavoriteItem.java
- src/main/java/com/zufar/icedlatte/favorite/entity/FavoriteList.java
- src/main/java/com/zufar/icedlatte/favorite/repository/FavoriteRepository.java
- src/main/resources/api-specs/favorite-openapi.yaml
endpoint for adding products to favorite list by product's ids
> create endpoint for adding products to favorite list

- README.md
- START.md
- pom.xml
- src/main/resources/application.yaml
[IL-225]: Swagger UI
* Added springdoc-openapi-starter-webmvc-ui
* removed extras (pom.xml)
* narrowed down packages to scan
TODO
> [IL-225]: Swagger UI

- .github/workflows/dev-branch-pr-build-and-test-pipeline.yaml
- pom.xml
[[IL-225]: Add SonarQube Analysis for DEV Pipeline](http://jira/browse/IL-226)
Added SonarQube job configuration
Results:
* [SQ Dashboard](http://31.132.209.218:63535/dashboard?id=com.zufar-project%3Aiced-latte)
* [Caught issue](https://github.com/Sunagatov/Iced-Latte/actions/runs/7136676940/job/19435490433?pr=182#step:6:308)
> [IL-226] SonarQube Analysis in GitHub actions

- src/main/java/com/zufar/icedlatte/product/api/ProductApi.java
- src/main/java/com/zufar/icedlatte/product/api/ProductApiImpl.java
- src/main/java/com/zufar/icedlatte/product/api/ProductsProvider.java
- src/main/java/com/zufar/icedlatte/product/endpoint/ProductsEndpoint.java
- src/main/java/com/zufar/icedlatte/product/exception/ProductNotFoundException.java
- src/main/resources/api-specs/product-openapi.yaml
- src/test/java/com/zufar/icedlatte/product/endpoint/ProductsEndpointTest.java
- src/test/resources/product/model/schema/product-list-by-id-schema.json
[[IL-255]: Add getProducts by list of IDs endpoint](http://jira/browse/IL-255)
- added ProductsProvider class with logic for retrieving products by IDs
- added new endpoint tests
- updated `ProductNotFoundException.java`
- updated `product-openapi.yaml`
> IL-255]: Add getProducts by list of IDs endpoint

- src/test/java/com/zufar/icedlatte/security/endpoint/SecurityEndpointTest.java
- src/test/java/com/zufar/icedlatte/test/config/RestAssertion.java
- src/test/resources/security/model/schema/security-schema-failed.json
- src/test/resources/security/model/schema/security-schema.json
- src/test/resources/security/model/security-authenticate-incorrect-password.json
- src/test/resources/security/model/security-authenticate-not-found-user.json
- src/test/resources/security/model/security-authenticate.json
- src/test/resources/security/model/security-registration-empty-email.json
- src/test/resources/security/model/security-registration-empty-password.json
- src/test/resources/security/model/security-registration-for-auth.json
- src/test/resources/security/model/security-registration-length-email-less-eight-word.json
- src/test/resources/security/model/security-registration-length-email-more-128-word.json
- src/test/resources/security/model/security-registration-length-last-name-less-two-word.json
- src/test/resources/security/model/security-registration-length-last-name-more-128-word.json
- src/test/resources/security/model/security-registration-length-name-less-two-word.json
- src/test/resources/security/model/security-registration-length-name-more-128-word.json
- src/test/resources/security/model/security-registration-length-password-less-eight-characters.json
- src/test/resources/security/model/security-registration-length-password-more-128-characters.json
- src/test/resources/security/model/security-registration-not-unique-email.json
- src/test/resources/security/model/security-registration-password-without-word.json
- src/test/resources/security/model/security-registration-without-last-name.json
- src/test/resources/security/model/security-registration-without-name.json
- src/test/resources/security/model/security-registration.json
add:
- 21 json files for sending a request and checking the response
- Class with test methods
- Change class RestAssertion
> IL-258: Create e2e test for Security package

- docker-compose.local.yml
- src/main/java/com/zufar/icedlatte/ApplicationMigration.java
- src/main/java/com/zufar/icedlatte/email/api/token/TokenGenerator.java
- src/main/java/com/zufar/icedlatte/email/api/token/TokenTimeExpirationCache.java
- src/main/java/com/zufar/icedlatte/email/exception/InvalidTokenException.java
- src/main/java/com/zufar/icedlatte/email/exception/MessageBuilderNotFoundException.java
- src/main/java/com/zufar/icedlatte/email/exception/TokenTimeExpiredException.java
- src/main/java/com/zufar/icedlatte/email/sender/AbstractEmailSender.java
- src/main/java/com/zufar/icedlatte/email/sender/EmailConfirmation.java
- src/main/java/com/zufar/icedlatte/favorite/converter/FavoriteListDtoConverter.java
- src/main/java/com/zufar/icedlatte/security/endpoint/UserSecurityEndpoint.java
[BE bug] Swagger is unavailable due to Minio migration exception
- added volume for pictures to `docker-compose.local.yml`
- added path to dir to log message
**Before**:
```log
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
iced-latte-backend  | 2024-01-23 00:56:20,231 [main] ERROR o.s.boot.SpringApplication      - Application run failed
iced-latte-backend  | java.lang.IllegalStateException: Failed to execute ApplicationRunner
iced-latte-backend  |   at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
iced-latte-backend  | Caused by: java.lang.IllegalArgumentException: Must provide a directory to …
```
> Minio: added volume for pictures to docker-compose.local.yml

- src/main/java/com/zufar/icedlatte/security/endpoint/UserSecurityEndpoint.java
- src/main/resources/api-specs/security-openapi.yaml
@Sunagatov @yevr19 @annstriganova
> IL-267: Create Refresh JWT Token (fix swagger)

- src/main/java/com/zufar/icedlatte/email/api/token/TokenCache.java
- src/main/java/com/zufar/icedlatte/email/api/token/TokenGenerator.java
- src/main/java/com/zufar/icedlatte/email/api/token/TokenManager.java
- src/main/java/com/zufar/icedlatte/email/exception/EmailExceptionHandler.java
- src/main/java/com/zufar/icedlatte/email/exception/IncorrectTokenException.java
- src/main/java/com/zufar/icedlatte/email/exception/IncorrectTokenFormatException.java
- src/main/java/com/zufar/icedlatte/email/exception/TokenTimeExpiredException.java
- src/main/java/com/zufar/icedlatte/security/dto/ConfirmEmailRequest.java
changed 404 exception to 400
add token validation
> email confirmation bag fix

- src/main/resources/application.yaml
> IL-267: temp reduce tokens ttl

- docker-compose.local.yml
- src/main/java/com/zufar/icedlatte/common/config/AWSConfig.java
- src/main/java/com/zufar/icedlatte/email/api/EmailTokenConformer.java
- src/main/java/com/zufar/icedlatte/user/dto/ConfirmEmailRequest.java
- src/main/java/com/zufar/icedlatte/user/endpoint/UserEndpoint.java
- src/main/resources/api-specs/user-openapi.yaml
> IL-282: Reset Password with email confirmation

- pom.xml
- src/main/java/com/zufar/icedlatte/astartup/ProductsReviewsAndRatingInfoUpdater.java
- src/main/java/com/zufar/icedlatte/favorite/converter/FavoriteListDtoConverter.java
- src/main/java/com/zufar/icedlatte/product/api/GetProductsRequestValidator.java
- src/main/java/com/zufar/icedlatte/product/api/PageableProductsProvider.java
- src/main/java/com/zufar/icedlatte/product/api/ProductUpdater.java
- src/main/java/com/zufar/icedlatte/product/api/rating/ProductAverageRatingUpdater.java
- src/main/java/com/zufar/icedlatte/product/converter/ProductInfoDtoConverter.java
- src/main/java/com/zufar/icedlatte/product/endpoint/ProductsEndpoint.java
- src/main/java/com/zufar/icedlatte/product/entity/ProductInfo.java
- src/main/java/com/zufar/icedlatte/product/exception/GetProductsBadRequestException.java
- src/main/java/com/zufar/icedlatte/product/exception/handler/ProductExceptionHandler.java
- src/main/java/com/zufar/icedlatte/product/repository/ProductInfoRepository.java
- src/main/java/com/zufar/icedlatte/review/api/ProductReviewCreator.java
- src/main/resources/api-specs/product-openapi.yaml
- src/main/resources/db/changelog/version-1.0/19.07.2023.part1.create-product-table.sql
- src/main/resources/db/changelog/version-1.0/19.07.2023.part2.insert-product-data.sql
- src/test/java/com/zufar/icedlatte/cart/stub/CartDtoTestStub.java
- src/test/java/com/zufar/icedlatte/order/stub/OrderDtoTestStub.java
New features:
- Added filtering by price_from, price_to, minimum_average_rating, brand_names, seller_names
- Added sorting by average_rating, reviews_count
- Database migration scripts were updated
- Swagger contracts were updated
> New Sorting and Filtering features were added for Product's Catalog 

- src/main/java/com/zufar/icedlatte/email/api/EmailTokenSender.java
- src/main/java/com/zufar/icedlatte/email/api/token/TokenCache.java
- src/main/java/com/zufar/icedlatte/security/endpoint/UserSecurityEndpoint.java
- src/main/resources/api-specs/security-openapi.yaml
- src/main/resources/application.yaml
- src/test/java/com/zufar/icedlatte/review/endpoint/ProductReviewEndpointTest.java
- src/test/resources/application-test.yaml
IL- endpoint get verification email code for test: POST /api/v1/auth/email/code
> IL- endpoint get verification email code for test

- .github/workflows/dev-branch-pr-build-and-test-pipeline.yaml
- Dockerfile
- Dockerfile.local
- docker-compose.local.yml
- pom.xml
[[GH Issue 285]: Update Java version from 17 to 21
](https://github.com/Sunagatov/Iced-Latte/issues/285)
- updated docker configuration
> Update Java version from 17 to 21

- src/main/java/com/zufar/icedlatte/favorite/converter/FavoriteListDtoConverter.java
- src/main/java/com/zufar/icedlatte/favorite/converter/ListOfFavoriteProductsDtoConverter.java
- src/main/java/com/zufar/icedlatte/review/api/ProductReviewsStatisticsProvider.java
- src/main/java/com/zufar/icedlatte/review/converter/ProductReviewDtoConverter.java
- src/test/java/com/zufar/icedlatte/favorite/converter/FavoriteItemDtoConverterTest.java
- src/test/java/com/zufar/icedlatte/favorite/converter/FavoriteListDtoConverterTest.java
- src/test/java/com/zufar/icedlatte/favorite/converter/ListOfFavoriteProductsDtoConverterTest.java
- src/test/java/com/zufar/icedlatte/review/api/ProductReviewsStatisticsProviderTest.java
- src/test/java/com/zufar/icedlatte/review/converter/ProductReviewDtoConverterTest.java
Cherry-picked Victoria's commits from https://github.com/Sunagatov/Iced-Latte/pull/295 and fixed tests that were failing after 1130cc9d1ad3dc488033c283cdefcdc68146a264 (UserEntity was deleted in FavoriteListEntity)
> COPY of #295: added some mappers by Victoria Ziborova

- src/main/java/com/zufar/icedlatte/review/validator/ProductReviewValidator.java
Changed arguments order when throwing new exception
[#314](https://github.com/Sunagatov/Iced-Latte/issues/314)
> [ISSUE #314] Fix ProductReviewValidator to send correct exception

- src/main/java/com/zufar/icedlatte/review/validator/ProductReviewValidator.java
> Issue #310  - handled wide space with EmptyProductReviewException

- config/checkstyle/checkstyle-author.xsl
- config/checkstyle/checkstyle.xml
- config/checkstyle/pre-commit
- pom.xml
Add Code Style file #31
apply [google check style](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml)
if want check style by pre commit, copy to git hooks folder
> chore: apply checkstytle

- src/main/java/com/zufar/icedlatte/order/entity/Order.java
- src/main/java/com/zufar/icedlatte/order/entity/OrderItem.java
- src/main/java/com/zufar/icedlatte/security/api/ResetLoginAttemptsService.java
This pull request suggests several minor identifier name changes for improved clarity and understandability.
> Refactored Identifiers

- src/main/java/com/zufar/icedlatte/order/api/OrderCreator.java
- src/main/java/com/zufar/icedlatte/order/api/OrderEntityCreator.java
- src/main/java/com/zufar/icedlatte/order/entity/Order.java
- src/main/java/com/zufar/icedlatte/payment/api/WebhookEventProcessor.java
- src/main/resources/db/changelog/version-1.0/07.01.2024.part1.create-order-table.sql
[[GH-342]  Fixed POST /stripe/webhook throws null value in column "address_id" even if address was specified in account](https://github.com/Sunagatov/Iced-Latte/issues/342)
- generate order_id manuallly
- use `UserEntity` instead of DTO
- add explicit constraint to DB migrations file
> [GH-342] Fixed POST /stripe/webhook throws null value in column "address_id" even if address was specified in account
